// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoNvl0T7WpIABrIas1zSwIUMEyxz8IuIU',
    appId: '1:494465541469:web:e5eec25c8f60f6c224b4b4',
    messagingSenderId: '494465541469',
    projectId: 'prep50',
    authDomain: 'prep50.firebaseapp.com',
    storageBucket: 'prep50.appspot.com',
    measurementId: 'G-4PQ01EZZ6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvVrSEXJ-mYQSABrL-cpk5cFqRyhGxVMs',
    appId: '1:494465541469:android:21c4b4e7651ff4e924b4b4',
    messagingSenderId: '494465541469',
    projectId: 'prep50',
    storageBucket: 'prep50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBShKnFWieD5Db_95ZHfiGkJE4y2mGLXeU',
    appId: '1:494465541469:ios:f34b0f051672de7c24b4b4',
    messagingSenderId: '494465541469',
    projectId: 'prep50',
    storageBucket: 'prep50.appspot.com',
    androidClientId: '494465541469-h692obeuvsvsenvongg3rfju0reemdu8.apps.googleusercontent.com',
    iosClientId: '494465541469-s2klu00oefospq810uapud4kehjrmt5j.apps.googleusercontent.com',
    iosBundleId: 'com.prep50.prep50',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBShKnFWieD5Db_95ZHfiGkJE4y2mGLXeU',
    appId: '1:494465541469:ios:1556ae00ba99971124b4b4',
    messagingSenderId: '494465541469',
    projectId: 'prep50',
    storageBucket: 'prep50.appspot.com',
    androidClientId: '494465541469-h692obeuvsvsenvongg3rfju0reemdu8.apps.googleusercontent.com',
    iosClientId: '494465541469-g4ooq4mf5b9fj24i7l2b4i53lo4stsge.apps.googleusercontent.com',
    iosBundleId: 'com.example.prep50',
  );
}
